package cli

import (
	"bytes"
	"errors"
	"strings"

	"github.com/spf13/cobra"
)

func newShellCompletionCommand(root *cobra.Command) *cobra.Command {
	return &cobra.Command{
		Use:       "completion [bash|zsh|fish|powershell]",
		Short:     "Generate shell completion",
		Args:      cobra.ExactArgs(1),
		ValidArgs: []string{"bash", "zsh", "fish", "powershell"},
		RunE: func(command *cobra.Command, args []string) error {
			switch args[0] {
			case "bash":
				return root.GenBashCompletionV2(command.OutOrStdout(), true)
			case "zsh":
				return root.GenZshCompletion(command.OutOrStdout())
			case "fish":
				return root.GenFishCompletion(command.OutOrStdout(), true)
			case "powershell":
				var generated bytes.Buffer
				if err := root.GenPowerShellCompletion(&generated); err != nil {
					return err
				}
				script := generated.String()
				marker := "    # First disable ActiveHelp which is not supported for Powershell"
				escapeCurrent := `    if ($WordToComplete -like '@*') {
        $RequestComp = $RequestComp.Substring(0, $RequestComp.Length - $WordToComplete.Length) + [char]96 + $WordToComplete
    }

`
				script = strings.Replace(script, marker, escapeCurrent+marker, 1)
				if script == generated.String() {
					return errors.New("generated PowerShell completion has an unsupported command shape")
				}
				_, err := command.OutOrStdout().Write([]byte(script))
				return err
			default:
				return errors.New("unsupported shell")
			}
		},
	}
}
